#############################################################################
# Makefile for building: scope500px
# Generated by qmake (3.0) (Qt 5.0.2) on: Tue Jan 14 19:43:34 2014
# Project:  scope500px.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile scope500px.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -pthread -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -pthread -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/usr/share/qt5/mkspecs/linux-g++-64 -I. -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/unity/unity -I/usr/include/gio-unix-2.0 -I/usr/include/dee-1.0 -I/usr/include/gee-1.0 -I/usr/include/libdbusmenu-glib-0.4
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -ltidy -lcurl -pthread -lunity -ldee-1.0 -lgee -ldbusmenu-glib -lgthread-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = scope500px.c \
		scope500px-photo-parser-func.c 
OBJECTS       = scope500px.o \
		scope500px-photo-parser-func.o
DIST          = /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/shell-unix.conf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_clucene.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_v8.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/unix/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		scope500px.pro \
		scope500px.pro
QMAKE_TARGET  = scope500px
DESTDIR       = 
TARGET        = scope500px


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): servicefilegen $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: scope500px.pro /usr/share/qt5/mkspecs/linux-g++-64/qmake.conf /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/shell-unix.conf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_clucene.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_v8.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/unix/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		scope500px.pro
	$(QMAKE) -o Makefile scope500px.pro
/usr/share/qt5/mkspecs/features/spec_pre.prf:
/usr/share/qt5/mkspecs/common/shell-unix.conf:
/usr/share/qt5/mkspecs/common/unix.conf:
/usr/share/qt5/mkspecs/common/linux.conf:
/usr/share/qt5/mkspecs/common/gcc-base.conf:
/usr/share/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt5/mkspecs/common/g++-base.conf:
/usr/share/qt5/mkspecs/common/g++-unix.conf:
/usr/share/qt5/mkspecs/qconfig.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_clucene.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_designercomponents.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_v8.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/share/qt5/mkspecs/features/qt_functions.prf:
/usr/share/qt5/mkspecs/features/qt_config.prf:
/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/share/qt5/mkspecs/features/spec_post.prf:
/usr/share/qt5/mkspecs/features/exclusive_builds.prf:
/usr/share/qt5/mkspecs/features/default_pre.prf:
/usr/share/qt5/mkspecs/features/unix/default_pre.prf:
/usr/share/qt5/mkspecs/features/resolve_config.prf:
/usr/share/qt5/mkspecs/features/default_post.prf:
/usr/share/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt5/mkspecs/features/warn_on.prf:
/usr/share/qt5/mkspecs/features/wayland-scanner.prf:
/usr/share/qt5/mkspecs/features/testcase_targets.prf:
/usr/share/qt5/mkspecs/features/exceptions.prf:
/usr/share/qt5/mkspecs/features/yacc.prf:
/usr/share/qt5/mkspecs/features/lex.prf:
scope500px.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile scope500px.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/scope500px1.0.0 || mkdir -p .tmp/scope500px1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/scope500px1.0.0/ && (cd `dirname .tmp/scope500px1.0.0` && $(TAR) scope500px1.0.0.tar scope500px1.0.0 && $(COMPRESS) scope500px1.0.0.tar) && $(MOVE) `dirname .tmp/scope500px1.0.0`/scope500px1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/scope500px1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) /home/shuduo/work/unity-scope/scope500px/data/unity-scope-scope500px.service scope500px /home/shuduo/work/unity-scope/scope500px/data/*~
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


servicefilegen:
	sed -e "s,\(Exec=\).*$$,\1/usr/lib/x86_64-linux-gnu/unity-scope-scope500px/scope500px," /home/shuduo/work/unity-scope/scope500px/data/unity-scope-scope500px.service.in > /home/shuduo/work/unity-scope/scope500px/data/unity-scope-scope500px.service

check: first

compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

scope500px.o: scope500px.c /usr/include/unity/unity/unity.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/include/glib-2.0/gio/gio.h \
		/usr/include/glib-2.0/gio/giotypes.h \
		/usr/include/glib-2.0/gio/gioenums.h \
		/usr/include/glib-2.0/gio/gaction.h \
		/usr/include/glib-2.0/gio/gactiongroup.h \
		/usr/include/glib-2.0/gio/gactiongroupexporter.h \
		/usr/include/glib-2.0/gio/gactionmap.h \
		/usr/include/glib-2.0/gio/gappinfo.h \
		/usr/include/glib-2.0/gio/gapplication.h \
		/usr/include/glib-2.0/gio/gapplicationcommandline.h \
		/usr/include/glib-2.0/gio/gasyncinitable.h \
		/usr/include/glib-2.0/gio/ginitable.h \
		/usr/include/glib-2.0/gio/gasyncresult.h \
		/usr/include/glib-2.0/gio/gbufferedinputstream.h \
		/usr/include/glib-2.0/gio/gfilterinputstream.h \
		/usr/include/glib-2.0/gio/ginputstream.h \
		/usr/include/glib-2.0/gio/gbufferedoutputstream.h \
		/usr/include/glib-2.0/gio/gfilteroutputstream.h \
		/usr/include/glib-2.0/gio/goutputstream.h \
		/usr/include/glib-2.0/gio/gbytesicon.h \
		/usr/include/glib-2.0/gio/gcancellable.h \
		/usr/include/glib-2.0/gio/gcharsetconverter.h \
		/usr/include/glib-2.0/gio/gconverter.h \
		/usr/include/glib-2.0/gio/gcontenttype.h \
		/usr/include/glib-2.0/gio/gconverterinputstream.h \
		/usr/include/glib-2.0/gio/gconverteroutputstream.h \
		/usr/include/glib-2.0/gio/gcredentials.h \
		/usr/include/glib-2.0/gio/gdatainputstream.h \
		/usr/include/glib-2.0/gio/gdataoutputstream.h \
		/usr/include/glib-2.0/gio/gdbusaddress.h \
		/usr/include/glib-2.0/gio/gdbusauthobserver.h \
		/usr/include/glib-2.0/gio/gdbusconnection.h \
		/usr/include/glib-2.0/gio/gdbuserror.h \
		/usr/include/glib-2.0/gio/gdbusintrospection.h \
		/usr/include/glib-2.0/gio/gdbusmessage.h \
		/usr/include/glib-2.0/gio/gdbusmethodinvocation.h \
		/usr/include/glib-2.0/gio/gdbusnameowning.h \
		/usr/include/glib-2.0/gio/gdbusnamewatching.h \
		/usr/include/glib-2.0/gio/gdbusproxy.h \
		/usr/include/glib-2.0/gio/gdbusserver.h \
		/usr/include/glib-2.0/gio/gdbusutils.h \
		/usr/include/glib-2.0/gio/gdrive.h \
		/usr/include/glib-2.0/gio/gemblemedicon.h \
		/usr/include/glib-2.0/gio/gicon.h \
		/usr/include/glib-2.0/gio/gemblem.h \
		/usr/include/glib-2.0/gio/gfileattribute.h \
		/usr/include/glib-2.0/gio/gfileenumerator.h \
		/usr/include/glib-2.0/gio/gfile.h \
		/usr/include/glib-2.0/gio/gfileicon.h \
		/usr/include/glib-2.0/gio/gfileinfo.h \
		/usr/include/glib-2.0/gio/gfileinputstream.h \
		/usr/include/glib-2.0/gio/gfileiostream.h \
		/usr/include/glib-2.0/gio/giostream.h \
		/usr/include/glib-2.0/gio/gioerror.h \
		/usr/include/glib-2.0/gio/gfilemonitor.h \
		/usr/include/glib-2.0/gio/gfilenamecompleter.h \
		/usr/include/glib-2.0/gio/gfileoutputstream.h \
		/usr/include/glib-2.0/gio/ginetaddress.h \
		/usr/include/glib-2.0/gio/ginetaddressmask.h \
		/usr/include/glib-2.0/gio/ginetsocketaddress.h \
		/usr/include/glib-2.0/gio/gsocketaddress.h \
		/usr/include/glib-2.0/gio/gioenumtypes.h \
		/usr/include/glib-2.0/gio/giomodule.h \
		/usr/include/glib-2.0/gmodule.h \
		/usr/include/glib-2.0/gio/gioscheduler.h \
		/usr/include/glib-2.0/gio/gloadableicon.h \
		/usr/include/glib-2.0/gio/gmemoryinputstream.h \
		/usr/include/glib-2.0/gio/gmemoryoutputstream.h \
		/usr/include/glib-2.0/gio/gmount.h \
		/usr/include/glib-2.0/gio/gmountoperation.h \
		/usr/include/glib-2.0/gio/gnativevolumemonitor.h \
		/usr/include/glib-2.0/gio/gvolumemonitor.h \
		/usr/include/glib-2.0/gio/gnetworkaddress.h \
		/usr/include/glib-2.0/gio/gnetworkmonitor.h \
		/usr/include/glib-2.0/gio/gnetworkservice.h \
		/usr/include/glib-2.0/gio/gpermission.h \
		/usr/include/glib-2.0/gio/gpollableinputstream.h \
		/usr/include/glib-2.0/gio/gpollableoutputstream.h \
		/usr/include/glib-2.0/gio/gpollableutils.h \
		/usr/include/glib-2.0/gio/gpropertyaction.h \
		/usr/include/glib-2.0/gio/gproxy.h \
		/usr/include/glib-2.0/gio/gproxyaddress.h \
		/usr/include/glib-2.0/gio/gproxyaddressenumerator.h \
		/usr/include/glib-2.0/gio/gsocketaddressenumerator.h \
		/usr/include/glib-2.0/gio/gproxyresolver.h \
		/usr/include/glib-2.0/gio/gresolver.h \
		/usr/include/glib-2.0/gio/gresource.h \
		/usr/include/glib-2.0/gio/gseekable.h \
		/usr/include/glib-2.0/gio/gsettingsschema.h \
		/usr/include/glib-2.0/gio/gsettings.h \
		/usr/include/glib-2.0/gio/gsimpleaction.h \
		/usr/include/glib-2.0/gio/gsimpleactiongroup.h \
		/usr/include/glib-2.0/gio/gsimpleasyncresult.h \
		/usr/include/glib-2.0/gio/gsimplepermission.h \
		/usr/include/glib-2.0/gio/gsocketclient.h \
		/usr/include/glib-2.0/gio/gsocketconnectable.h \
		/usr/include/glib-2.0/gio/gsocketconnection.h \
		/usr/include/glib-2.0/gio/gsocket.h \
		/usr/include/glib-2.0/gio/gsocketcontrolmessage.h \
		/usr/include/glib-2.0/gio/gsocketlistener.h \
		/usr/include/glib-2.0/gio/gsocketservice.h \
		/usr/include/glib-2.0/gio/gsrvtarget.h \
		/usr/include/glib-2.0/gio/gsimpleproxyresolver.h \
		/usr/include/glib-2.0/gio/gtask.h \
		/usr/include/glib-2.0/gio/gtcpconnection.h \
		/usr/include/glib-2.0/gio/gtcpwrapperconnection.h \
		/usr/include/glib-2.0/gio/gtestdbus.h \
		/usr/include/glib-2.0/gio/gthemedicon.h \
		/usr/include/glib-2.0/gio/gthreadedsocketservice.h \
		/usr/include/glib-2.0/gio/gtlsbackend.h \
		/usr/include/glib-2.0/gio/gtlscertificate.h \
		/usr/include/glib-2.0/gio/gtlsclientconnection.h \
		/usr/include/glib-2.0/gio/gtlsconnection.h \
		/usr/include/glib-2.0/gio/gtlsdatabase.h \
		/usr/include/glib-2.0/gio/gtlsfiledatabase.h \
		/usr/include/glib-2.0/gio/gtlsinteraction.h \
		/usr/include/glib-2.0/gio/gtlsserverconnection.h \
		/usr/include/glib-2.0/gio/gtlspassword.h \
		/usr/include/glib-2.0/gio/gvfs.h \
		/usr/include/glib-2.0/gio/gvolume.h \
		/usr/include/glib-2.0/gio/gzlibcompressor.h \
		/usr/include/glib-2.0/gio/gzlibdecompressor.h \
		/usr/include/glib-2.0/gio/gdbusinterface.h \
		/usr/include/glib-2.0/gio/gdbusinterfaceskeleton.h \
		/usr/include/glib-2.0/gio/gdbusobject.h \
		/usr/include/glib-2.0/gio/gdbusobjectskeleton.h \
		/usr/include/glib-2.0/gio/gdbusobjectproxy.h \
		/usr/include/glib-2.0/gio/gdbusobjectmanager.h \
		/usr/include/glib-2.0/gio/gdbusobjectmanagerclient.h \
		/usr/include/glib-2.0/gio/gdbusobjectmanagerserver.h \
		/usr/include/glib-2.0/gio/gdbusactiongroup.h \
		/usr/include/glib-2.0/gio/gremoteactiongroup.h \
		/usr/include/glib-2.0/gio/gmenumodel.h \
		/usr/include/glib-2.0/gio/gmenu.h \
		/usr/include/glib-2.0/gio/gmenuexporter.h \
		/usr/include/glib-2.0/gio/gdbusmenumodel.h \
		/usr/include/dee-1.0/dee.h \
		/usr/include/dee-1.0/dee-peer.h \
		/usr/include/dee-1.0/dee-server.h \
		/usr/include/dee-1.0/dee-client.h \
		/usr/include/dee-1.0/dee-model.h \
		/usr/include/dee-1.0/dee-model-reader.h \
		/usr/include/dee-1.0/dee-serializable-model.h \
		/usr/include/dee-1.0/dee-proxy-model.h \
		/usr/include/dee-1.0/dee-sequence-model.h \
		/usr/include/dee-1.0/dee-shared-model.h \
		/usr/include/dee-1.0/dee-filter-model.h \
		/usr/include/dee-1.0/dee-filter.h \
		/usr/include/dee-1.0/dee-index.h \
		/usr/include/dee-1.0/dee-term-list.h \
		/usr/include/dee-1.0/dee-result-set.h \
		/usr/include/dee-1.0/dee-analyzer.h \
		/usr/include/dee-1.0/dee-hash-index.h \
		/usr/include/dee-1.0/dee-tree-index.h \
		/usr/include/dee-1.0/dee-text-analyzer.h \
		/usr/include/dee-1.0/dee-serializable.h \
		/usr/include/dee-1.0/dee-resource-manager.h \
		/usr/include/dee-1.0/dee-file-resource-manager.h \
		/usr/include/dee-1.0/dee-transaction.h \
		/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/client.h \
		/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/menuitem.h \
		/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/types.h \
		/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/dbusmenu-glib.h \
		/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/menuitem-proxy.h \
		/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/server.h \
		/usr/include/libdbusmenu-glib-0.4/libdbusmenu-glib/enum-types.h \
		config.h \
		scope500px-photo-parser-func.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o scope500px.o scope500px.c

scope500px-photo-parser-func.o: scope500px-photo-parser-func.c /usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o scope500px-photo-parser-func.o scope500px-photo-parser-func.c

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/unity-scope-scope500px || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/unity-scope-scope500px
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/unity-scope-scope500px/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/unity-scope-scope500px/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/unity-scope-scope500px/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/unity-scope-scope500px/ 


install_scopefile: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/unity/scopes/graphics || mkdir -p $(INSTALL_ROOT)/usr/share/unity/scopes/graphics
	-$(INSTALL_FILE) /home/shuduo/work/unity-scope/scope500px/data/scope500px.scope $(INSTALL_ROOT)/usr/share/unity/scopes/graphics/

uninstall_scopefile: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/unity/scopes/graphics/scope500px.scope
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/unity/scopes/graphics/ 


install_servicefile: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/dbus-1/services || mkdir -p $(INSTALL_ROOT)/usr/share/dbus-1/services
	-$(INSTALL_FILE) /home/shuduo/work/unity-scope/scope500px/data/unity-scope-scope500px.service $(INSTALL_ROOT)/usr/share/dbus-1/services/

uninstall_servicefile: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/dbus-1/services/unity-scope-scope500px.service
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/dbus-1/services/ 


install:  install_target install_scopefile install_servicefile  FORCE

uninstall: uninstall_target uninstall_scopefile uninstall_servicefile   FORCE

FORCE:

