CC=gcc
CFLAGS=-Wall -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include 
LDFLAGS=-lglib-2.0 -lcurl -ltidy

OBJECTS=scope500px-photo-parser.o scope500px-photo-parser-func.o
SOURCES=scope500px-photo-parser.c scope500px-photo-parser-func.c

scope500px-photo-parser: $(OBJECTS)
	        $(CC) $(CFLAGS) $(OBJECTS) -o $@ $(LDFLAGS)

.PHONY:        clean

clean:
	        -rm -f scope500px-photo-parser *.o *~

